NewsPaper/NewsPaper/urls.py

from django.contrib import admin
from django.urls import path, include
from news.views import subscriptions


urlpatterns = [
   path('admin/', admin.site.urls),
   path('pages/', include('django.contrib.flatpages.urls')),
   path("authors/", include("allauth.urls")),
   path('news/', include('news.urls')),
   path('subscriptions/', subscriptions, name='subscriptions'),
]

NewsPaper/news/urls.py
from django.urls import path
from .views import NewsList, NewsDetail, PostCreate, PostSearch, PostUpdate, PostDelete, subscriptions
from django.views.decorators.cache import cache_page


urlpatterns = [
   path('', cache_page(60)(NewsList.as_view()), name='post_list'),
   path('<int:pk>', cache_page(300)(NewsDetail.as_view()), name='news_detail'),
   path('create/', cache_page(60)(PostCreate.as_view()), name='post_create'),
   path('articles/create/', PostCreate.as_view(), name='post_create'),
   path('search/',PostSearch.as_view(), name='search'),
   path('<int:pk>/edit/', PostUpdate.as_view(), name='post_update'),
   path('articles/<int:pk>/edit/', PostUpdate.as_view(), name='post_update'),
   path('<int:pk>/delete/', PostDelete.as_view(), name='post_delete'),
   path('articles/<int:pk>/delete/', PostDelete.as_view(), name='post_delete'),

]

NewsPaper/news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.urls import reverse
from django.core.cache import cache
#from django.db.models.functions import Coalesce если None коментов или постов


class Author(models.Model):
    authorUser = models.OneToOneField(User, on_delete=models.CASCADE)
    ratingAuthor = models.IntegerField(default=0)

    def update_rating(self):
        postRat = self.post_set.aggregate(postRating=Sum('rating'))
        pRat = 0
        pRat += postRat.get("postRating")

        commentRat = self.authorUser.comment_set.aggregate(commentRating=Sum('rating'))
        cRat = 0
        cRat += commentRat.get("commentRating")
        self.ratingAuthor = pRat * 3 + cRat
        self.save()


class Category(models.Model):
    category = models.CharField(max_length=64)
    subscribers = models.ManyToManyField(User, max_length=64, blank=True)
    def __str__(self):
        return self.category


class Post(models.Model):
    autor = models.ForeignKey(Author, on_delete=models.CASCADE)
    news = 'NW'
    article = "AC"

    NamePost = [
        (news, 'новость'),
        (article, 'статья')
    ]
    namePost = models.CharField(max_length=2, choices=NamePost, default='NW')
    timeCreate = models.DateTimeField(auto_now_add=True)
    postCategory = models.ManyToManyField(Category, through="PostCategory")
    heading = models.CharField(max_length=128)
    textPost = models.TextField()
    rating = models.IntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return self.textpost[0:123] + "..."

    def get_absolute_url(self):
        return reverse('news_detail', args=[str(self.id)])

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)  # сначала вызываем метод родителя, чтобы объект сохранился
        cache.delete(f'news-{self.pk}')  # затем удаляем его из кэша, чтобы сбросить его

class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)




class Comment(models.Model):
    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE)
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    dateCreation = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()


class Subscription(models.Model):
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )
    category = models.ForeignKey(
        to='Category',
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )

NewsPaper/templates/Post.html
{% extends 'flatpages/default.html' %}
{% load сustom_filters %}

{% block title %}
Post.heading
{% endblock title %}

{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Post</title>
        <tr>
            <td>{{ Post.heading|censor }}</td>
            <td>{{ Post.textPost|censor|truncatechars:20  }}</td>
            <td>{{ Post.timeCreate|date:'d M Y' }}</td>

        </tr>
</head>
<body>
{% endblock content %}
</body>
</html>

NewsPaper/templates/Posts.html
{% extends 'flatpages/default.html' %}

{% load сustom_filters %}

{% load custom_tags %}

{% block title %}
News
{% endblock title %}

{% block content %}
   <h1>Все новости</h1>

   <hr>

     {# Теперь будем проверять не request.user.is_authenticated, а конкретные права #}
    {% if perms.simpleapp.add_product %}
    <a href="{% url 'post_create' %}">Добавить товар</a>
    {% endif %}

   {% if Posts %}
       <table>
           <tr>
               <td>Название</td>
               <td>Текст</td>
               <td>Дата загрузки</td>
           </tr>

           {% for Post in Posts %}
           <tr>
               <td>{{ Post.heading|censor }}</td>
               <td>{{ Post.textPost|censor|truncatechars:20  }}</td>
               <td>{{ Post.timeCreate|date:'d M Y' }}</td>
                <td>
                    {# А здесь доступ для каждой ссылки теперь будем проверять отдельно #}
                    {% if perms.news.change_post %}
                    <a href="{% url 'post_update' pk=Post.id %}">Изменить</a>
                    {% endif %}
                    {% if perms.news.delete_product %}
                    <a href="{% url 'post_delete' Post.id %}">Удалить</a>
                    {% endif %}
                </td>

           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>Новостей нет!</h2>!
   {% endif %}

   {% if page_obj.has_previous %}
        <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
        {% endif%}
    {% endif %}

    {{page_obj.number}}

   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

NewsPaper/templates/mail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Новая статья от автора {{ Post.author }} из категории {{ Post.category }}</title>
</head>
<body>
    <h1> Здравствуйте, {{ user }}, на новостном портале появилась новая статья от автора {{ post.author }} из категории {{ post.category }}</h1>
    <p> {{ text }} </p>

    <p><a href="http://127.0.0.1:8000{{ post.get_absolute_url }}">Перейти на статью</a></p>

</body>
</html>

NewsPaper/templates/post_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление товара</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.name }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

NewsPaper/templates/post_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Новость</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

NewsPaper/templates/search.html
{% extends 'flatpages/default.html' %}

{% load custom_tags %}

{% block title %}
Search
{% endblock title %}

{% block content %}
   <h1>Все новости</h1>

   {# Добавляем форму, которая объединяет набор полей, которые будут отправляться в запросе #}
   <form action="" method="get">
       {# Переменная, которую мы передали через контекст, может сгенерировать нам форму с полями #}
       {{ filterset.form.as_p }}
       {# Добавим кнопку отправки данных формы #}
       <input type="submit" value="Найти" />
   </form>

   <hr>
   {% if Posts %}
       <table>
           <tr>
               <td>Название</td>
               <td>Текст</td>
               <td>Дата загрузки</td>
           </tr>

           {% for Post in Posts %}
           <tr>
               <td>{{ Post.heading}}</td>
               <td>{{ Post.textPost}}</td>
               <td>{{ Post.timeCreate|date:'d M Y' }}</td>

           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>Новостей нет!</h2>!
   {% endif %}

   {% if page_obj.has_previous %}
        <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
        {% endif%}
    {% endif %}

    {{page_obj.number}}

   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

NewsPaper/templates/subscriptions.html
{% extends 'flatpages/default.html' %}

{% block title %}
Subscriptions
{% endblock title %}

{% block content %}
    {% for category in categories  %}
        <p>
            {{ category }}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="category_id" value="{{ category.id }}" />

                {% if category.user_subscribed %}
                    <button disabled>Подписаться</button>
                    <button name="action" value="unsubscribe">Отписаться</button>
                {% else %}
                    <button name="action" value="subscribe">Подписаться</button>
                    <button disabled>Отписаться</button>
                {% endif %}
            </form>
        </p>
    {% endfor %}
{% endblock content %}